# -*- coding: utf-8 -*-
"""DJ Alex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TsHK25sKZXCUZU_tMeH5LugkJRePD0Fa
"""

import streamlit as st

# Lista de canciones
canciones = [
    {
        "titulo": "Ëcoute chérie",
        "artista": "Vendredi sur Mer",
        "url": "https://www.youtube.com/embed/Fc9YMzOoEr4"
    },
    {
        "titulo": "Feel u",
        "artista": "okayceci",
        "url": "https://www.youtube.com/embed/goigX3c-s4U"
    },
    {
        "titulo": "Crawler",
        "artista": "Joyhauser",
        "url": "https://www.youtube.com/embed/AxBPg9PGQgw"
    },
    {
        "titulo": "Stiefelblitz",
        "artista": "Jarhe 90",
        "url": "https://www.youtube.com/embed/S4msmM49RKY"
    },
    {
        "titulo": "Die Liebe Kommt nicht aus Berlin",
        "artista": "Brutalismus 3000",
        "url": "https://www.youtube.com/embed/BY1qkoUhcWQ"
    },
    {
        "titulo": "Antonio soffiantini detto tunin",
        "artista": "Carlo Savani",
        "url": "https://www.youtube.com/watch?v=KrqTPEow7rk"
    },
    {
        "titulo": "Jewells",
        "artista": "Cranes",
        "url": "https://www.youtube.com/watch?v=L8QE4k0T980"
    },
    {
        "titulo": "Running up that hill",
        "artista": "Kate Bush",
        "url": "https://www.youtube.com/watch?v=HYwNM1t9ltI"
    },
    {
        "titulo": "Interlude",
        "artista": "Reverend Baron",
        "url": "https://www.youtube.com/watch?v=nuRT3fm3KYE"
    },
    {
        "titulo": "Electrocution",
        "artista": "Automatic",
        "url": "https://www.youtube.com/watch?v=rvIlqj3bPXc"
    },
    {
        "titulo": "Highway",
        "artista": "Automatic",
        "url": "https://www.youtube.com/watch?v=T6yMjmlfw7M"
    },
    {
        "titulo": "I Can´t live in a living room",
        "artista": "Red Zebra",
        "url": "https://www.youtube.com/watch?v=Xvb_oRBjbcw"
    },
    {
        "titulo": "Supernature",
        "artista": "Cerrone",
        "url": "https://www.youtube.com/watch?v=7XMpqVmaQpg"
    },
    {
        "titulo": "Higher",
        "artista": "Ary",
        "url": "https://www.youtube.com/watch?v=WtAz6jc2mr0"
    },
    {
        "titulo": "Paris/Orly",
        "artista": "Deux",
        "url": "https://www.youtube.com/watch?v=XXIPOK1rc88"
    },
    {
        "titulo": "Game and Performance",
        "artista": "Deux",
        "url": "https://www.youtube.com/watch?v=E_lnQDnC3zU"
    },
    {
        "titulo": "Espresso",
        "artista": "Sabrina Carpenter",
        "url": "https://www.youtube.com/watch?v=51zjlMhdSTE"
    },
    {
        "titulo": "No habrá nadie en el mundo",
        "artista": "Bulka",
        "url": "https://www.youtube.com/watch?v=JETyhLQFJW4"
    },
    {
        "titulo": "Mlitary Fashion Show",
        "artista": "And One",
        "url": "https://www.youtube.com/watch?v=vwnLp67rrzY"
    },
    {
        "titulo": "Babes ofthe 80s",
        "artista": "Lebanon Hanover",
        "url": "https://www.youtube.com/watch?v=8kXFnLI1bzc"
    },
    {
        "titulo": "Pain",
        "artista": "Boy Hasher",
        "url": "https://www.youtube.com/watch?v=HYsTVlznT8I"
    }


]

st.title("El play list oficial del tio Alex")

# Seleccionar canción
opciones = [f"{c['titulo']} - {c['artista']}" for c in canciones]
seleccion = st.selectbox("Elige una canción:", opciones)

# Slider de volumen
volumen = st.slider('Volumen', min_value=0, max_value=100, value=50)

# Buscar URL seleccionada
cancion_actual = next(c for c in canciones if f"{c['titulo']} - {c['artista']}" == seleccion)

# Mostrar reproductor
st.markdown(f"""
    <iframe width="700" height="400"
    src="{cancion_actual['url']}?autoplay=1&volume={volumen}"
    frameborder="0" allow="autoplay; encrypted-media" allowfullscreen>
    </iframe>
""", unsafe_allow_html=True)

st.caption("El volumen puede que necesites ajustarlo directamente en YouTube. ")

# Personalización de diseño
st.markdown("""
<style>
    .stApp {
        background-color:  #00FF00;
    }
    .css-1d391kg {
        color:  #faf7f8;
    }
</style>
""", unsafe_allow_html=True)