# -*- coding: utf-8 -*-
"""DJ Alex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TsHK25sKZXCUZU_tMeH5LugkJRePD0Fa
"""

import streamlit as st

# Lista de canciones
canciones = [
    {
        "titulo": "Ëcoute chérie",
        "artista": "Vendredi sur Mer",
        "url": "https://www.youtube.com/embed/Fc9YMzOoEr4"
    },
    {
        "titulo": "Feel u",
        "artista": "okayceci",
        "url": "https://www.youtube.com/embed/goigX3c-s4U"
    },
    {
        "titulo": "Crawler",
        "artista": "Joyhauser",
        "url": "https://www.youtube.com/embed/AxBPg9PGQgw"
    },
    {
        "titulo": "Stiefelblitz",
        "artista": "Jarhe 90",
        "url": "https://www.youtube.com/embed/S4msmM49RKY"
    },
    {
        "titulo": "Die Liebe Kommt nicht aus Berlin",
        "artista": "Brutalismus 3000",
        "url": "https://www.youtube.com/embed/BY1qkoUhcWQ"
    }
]

st.title("🎵 Reproductor de YouTube")

# Seleccionar canción
opciones = [f"{c['titulo']} - {c['artista']}" for c in canciones]
seleccion = st.selectbox("Elige una canción:", opciones)

# Slider de volumen
volumen = st.slider('Volumen', min_value=0, max_value=100, value=50)

# Buscar URL seleccionada
cancion_actual = next(c for c in canciones if f"{c['titulo']} - {c['artista']}" == seleccion)

# Mostrar reproductor
st.markdown(f"""
    <iframe width="700" height="400"
    src="{cancion_actual['url']}?autoplay=1&volume={volumen}"
    frameborder="0" allow="autoplay; encrypted-media" allowfullscreen>
    </iframe>
""", unsafe_allow_html=True)

st.caption("El volumen puede que necesites ajustarlo directamente en YouTube. 🎶")